version: "2"

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  stastd:
    image: prom/statsd-exporter
    container_name: statsd
    ports:
      - "9102:9102"
      - "9125:9125/udp"
  prometheus:
    image: bitnami/prometheus
    container_name: prometheus
    volumes:
      - ./config/prometheus/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
      - prometheus_data:/opt/bitnami/prometheus/data
    command:
      - "--config.file=/opt/bitnami/prometheus/conf/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    expose:
      - 9090
    ports:
      - 9090:9090
  node-exporter:
    image: prom/node-exporter
    ports:
      - 9100:9100
    expose:
      - 9100
  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=foobar
      - GF_USERS_ALLOW_SIGN_UP=false
