{
 "title": "Latency View (Managed by Terraform)",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "status_code",
    "label": "status_code",
    "query": {
     "query": "label_values(request_latency_seconds_hist,status)"
    }
   },
   {
    "name": "endpoint",
    "label": "endpoint",
    "query": {
     "query": "label_values(request_latency_seconds_hist,endpoint)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Latency Summary",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "request_latency_seconds_hist{endpoint=\"$endpoint\", quantile=\"0.5\", status=\"$status_code\"}",
     "legendFormat": "P50"
    },
    {
     "expr": "request_latency_seconds_hist{endpoint=\"$endpoint\", quantile=\"0.9\", status=\"$status_code\"}",
     "legendFormat": "P90"
    },
    {
     "expr": "request_latency_seconds_hist{endpoint=\"$endpoint\", quantile=\"0.99\", status=\"$status_code\"}",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Latency Trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "request_latency_seconds_hist{endpoint=\"$endpoint\", status=\"$status_code\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expression": "$B / ($A +  $B)", "type": "math" }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(request_latency_seconds_hist_count{endpoint=\"$endpoint\", status=\"$status_code\"}[$__rate_interval])",
     "legendFormat": "{{service}}"
    }
   ]
  }
 ]
}